config/routes.rb
Tigerpass::Application.routes.draw do
  root :to => 'clubs#index'
  resources :clubs
  resources :events
  match 'attend/:event_id', to: 'events#attend'
  match 'unattend/:event_id', to: 'events#unattend'

  match 'fblogin', to: 'access#fblogin'
  match 'newuser', to: 'access#newuser'
  match 'ugauth', to: 'access#auth'
  match 'denied', to: 'access#denied'
  match 'ugonly', to: 'access#ugonly'
  match 'sendauth', to: 'access#sendauthemail'
  match 'createuser', to: 'access#finishuser'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TigerPass</title>
    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Lato:400,900|Open+Sans:400,600' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!-- Google Analytics -->
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-28953326-1']);
      _gaq.push(['_trackPageview']);
      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' :
      //'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </head>
  <body>
    <div id="centerColumn">
      <%= link_to root_url, id: "mainLogo" do %>
        <h1>TIGERPASS</h1>
      <% end %>

      <div id="shieldBorder">
        <div id="shield">
          <%= image_tag "shield.png" %>
        </div>
      </div>

      <br>
      <br>

      <%= yield %>

      <div class="dottedDivider"></div>
      <br>
      <br>
      <h3 id="bigDeal">
        Hey, we noticed you're kind of a big deal.
        <br>
        <%= link_to "Submit", new_event_path, class: "linkBorder" %> an upcoming event or <%= link_to "view", events_path, class: "linkBorder" %> your existing events.
      </h3>
      <br>
      <br>
      <div id="footerDivider"></div>
      <br>
      <div id="footer" style="text-align: center">
        <h3>Live Long and Prospect.</h3>
        <h5 style="font-size: 13px; padding-top: 5px">
          <a href="about.html" class="iframe linkBorder" >About</a> -
          <a class="linkBorder"
             href="mailto:tigerpassauth@gmail.com?subject=TigerPass Feedback">Contact</a> - 2012
        </h5>
        <div id="blackshield"><img id="blackshieldImg" style="margin-top: 10px;" src="<%= image_path("blackshield.png") %>" alt="" /></div>
      </div>
    </div>
  </body>
</html>